SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Definei size of player's ship
PLAYER_RADIUS = 20

# Player's turn speed
PLAYER_TURN_SPEED = 300

# Player's move speed
PLAYER_SPEED = 200

# Shot radius of shot
SHOT_RADIUS = 5

# Player bullet shoot speed
PLAYER_SHOOT_SPEED = 500